### ISSUE TITLE
pie chart binding data can not show

### ISSUE THREAD

**Issue by IvanJiang2019** [DataV-Team/datav.jiaminghi.com#7]
hi, i have a question as below,
url1: https://baijiahao.baidu.com/s?id=1659789987293640224&wfr=spider&for=pc
url2: http://datav.jiaminghi.com/demo/construction-data/index.html

url1 use the same demo page as url2, but why the first can display pie chart binded value, but the second not show it?  

here is my code: 

 createData () {
      const { randomExtend } = this

      let seriesdata = [
        { name: "pass", value: randomExtend(5000, 6000) },
        { name: "prevent", value: randomExtend(100, 150) },
        { name: "check", value: randomExtend(200, 300) }
      ]

      this.option = {
         series: [
                {
                  type: 'pie',
                  radius: '70%',
                  roseSort: false,
                  data: seriesdata,
                  roseType: true
                }
              ],
      	color: [ '#224590', '#f46827', '#4d99fc']
      };
    },

where is wrong?  
thanks for point it very much~
![ui](https://user-images.githubusercontent.com/52005954/75620986-02664680-5bca-11ea-89d0-2a419646499c.png)
![code](https://user-images.githubusercontent.com/52005954/75620994-245fc900-5bca-11ea-99fb-890b7fa11762.png)
![ui](https://user-images.githubusercontent.com/52005954/75620996-26c22300-5bca-11ea-91c5-c4a5cba026d0.png)

**Comment by jiaming743** [comment]
```html
```

**Comment by jiaming743** [comment]
This can be displayed normally.
Please try to upgrade to the latest version.

```html
<!DOCTYPE html>
<html>
<head>
  <title>DataV</title>
  <script src="https://unpkg.com/vue"></script>
  <script src="https://unpkg.com/@jiaminghi/data-view/dist/datav.map.vue.js"></script>
  <style>
    html, body, #app {
      width: 100%;
      height: 100%;
      margin: 0px;
      padding: 0px;
    }
  </style>
</head>
<body>
  <div id="app">
    <dv-charts :option="option" style="width: 400px;height: 400px;" />
  </div>

  <script>
    var app = new Vue({
      el: '#app',
      data () {
      	return {
      		option: {}
      	}
      },
      mounted () {
		let seriesdata = [
			{ name: "pass", value: 5555 },
			{ name: "prevent", value: 125 },
			{ name: "check", value: 299 }
		]
		this.option = {
		 	series: [
		        {
		          type: 'pie',
		          radius: '70%',
		          roseSort: false,
		          data: seriesdata,
		          roseType: true
		        }
		      ],
			color: [ '#224590', '#f46827', '#4d99fc']
		};
      }
    })
  </script>
</body>
</html>
```

**Comment by IvanJiang2019** [comment]
thanks for your response. 

I find the same .vue code, running in Chrome is ok, the picture  attached yesterday not show digital was run in Edge~~

The html you given is also ok in Chrome, but still not presnet in Edge.
![Chrome and Edge](https://user-images.githubusercontent.com/52005954/75639697-0f884180-5c6d-11ea-92a3-3051299ee8eb.png)

**Comment by jiaming743** [comment]
This maybe a compatibility issue.
Please use chrome.
